"use strict";
const API_URL="https://script.google.com/macros/s/AKfycbxPdMLeAlchVVZltW1knBOeNvQqgmL-qfaaGfDUZoIBqLd-DKVPK3uDy7qFmou91DvqzQ/exec";
const LOGOS={"PROY-0001":"./assets/logo-taxichurro.png","PROY-0002":"./assets/logo-compraya.png","PROY-0003":"./assets/logo-huellitas.png","PROY-0004":"./assets/logo-selvaviva.png"};
const s={projects:[],members:[],supports:{},filtered:[]};
const e={grid:q("#projects-grid"),status:q("#status-message"),empty:q("#empty-state"),search:q("#search-input"),campus:q("#campus-filter"),level:q("#level-filter"),grade:q("#grade-filter"),category:q("#category-filter"),clear:q("#clear-filters"),pc:q("#projects-count"),cc:q("#campuses-count"),catc:q("#categories-count"),sc:q("#students-count"),modal:q("#project-modal"),body:q("#modal-body"),toast:q("#toast")};
document.addEventListener("DOMContentLoaded",init);
function q(x){return document.querySelector(x)}
async function init(){bind();await load()}
function bind(){[e.search,e.campus,e.level,e.grade,e.category].forEach(x=>x.addEventListener(x.tagName==="INPUT"?"input":"change",filter));e.clear.addEventListener("click",clear);document.addEventListener("click",async ev=>{const d=ev.target.closest("[data-project-id]");if(d)openModal(d.dataset.projectId);const a=ev.target.closest("[data-support-id]");if(a)await support(a.dataset.supportId);if(ev.target.closest("[data-close-modal]"))closeModal()});document.addEventListener("keydown",ev=>{if(ev.key==="Escape")closeModal()})}
async function load(){try{const r=await fetch(`${API_URL}?action=all`,{cache:"no-store"});const j=await r.json();if(!j.success)throw Error(j.error||"API inválida");const d=j.data||{};s.projects=Array.isArray(d.proyectos)?d.proyectos:[];s.members=Array.isArray(d.integrantes)?d.integrantes:[];s.supports=d.apoyos||{};s.filtered=[...s.projects];fillFilters();stats();render(s.filtered);e.status.classList.add("hidden");e.grid.classList.remove("hidden")}catch(err){console.error(err);e.status.innerHTML=`<div style="font-size:2.5rem">⚠️</div><h3>No pudimos cargar la información</h3><p>Revisa Apps Script y vuelve a publicar una nueva versión.</p>`}}
function vals(f){return[...new Set(s.projects.map(x=>String(x[f]||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es",{numeric:true}))}
function setSel(sel,arr,label){sel.innerHTML=`<option value="">${label}</option>`;arr.forEach(v=>{const o=document.createElement("option");o.value=o.textContent=v;sel.appendChild(o)})}
function fillFilters(){setSel(e.campus,vals("sede"),"Todas");setSel(e.level,vals("nivel"),"Todos");setSel(e.grade,vals("grado"),"Todos");setSel(e.category,vals("categoria"),"Todas")}
function stats(){e.pc.textContent=s.projects.length;e.cc.textContent=vals("sede").length;e.catc.textContent=vals("categoria").length;e.sc.textContent=s.members.length}
function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim()}
function filter(){const z=norm(e.search.value);s.filtered=s.projects.filter(p=>{const txt=norm([p.proyecto,p.descripcion_corta,p.categoria,p.sede,p.nivel,p.grado].join(" "));return(!z||txt.includes(z))&&(!e.campus.value||p.sede===e.campus.value)&&(!e.level.value||p.nivel===e.level.value)&&(!e.grade.value||p.grado===e.grade.value)&&(!e.category.value||p.categoria===e.category.value)});render(s.filtered)}
function clear(){e.search.value=e.campus.value=e.level.value=e.grade.value=e.category.value="";s.filtered=[...s.projects];render(s.filtered)}
function render(arr){e.grid.innerHTML="";e.empty.classList.toggle("hidden",arr.length>0);arr.forEach(p=>e.grid.appendChild(card(p)))}
function card(p){const a=document.createElement("article");a.className="card";const img=LOGOS[p.id]||url(p.logo||p.imagen),proto=url(p.prototipo),doc=url(p.documento),on=localStorage.getItem(`agora-supported-${p.id}`)==="1",count=Number(s.supports[p.id]||0);a.innerHTML=`<div class="image"><span class="badge">${esc(p.estado||"Proyecto")}</span>${img?`<img src="${attr(img)}" alt="Logo de ${attr(p.proyecto||"")}">`:`<div style="font-size:4rem">💡</div>`}</div><div class="content"><div class="meta"><span>🏫 ${esc(p.sede||"Ágora")}</span><span>🎓 ${esc(p.grado||p.nivel||"")}</span><span>💡 ${esc(p.categoria||"Innovación")}</span></div><h3>${esc(p.proyecto||"Proyecto Ágora")}</h3><p class="desc">${esc(p.descripcion_corta||"")}</p><div class="actions"><button class="btn outline" data-project-id="${attr(p.id||"")}">Conocer proyecto</button>${proto?`<a class="btn primary" href="${attr(proto)}" target="_blank" rel="noopener">Probar prototipo</a>`:""}${doc?`<a class="btn orange" href="${attr(doc)}" target="_blank" rel="noopener">Ver documento</a>`:""}</div><div class="support"><button class="btn support-btn ${on?"on":""}" data-support-id="${attr(p.id||"")}">${on?"❤️ Apoyado":"🤍 Apoyar proyecto"}</button><span class="count">${count} apoyo${count===1?"":"s"}</span></div></div>`;return a}
async function support(id){const k=`agora-supported-${id}`;if(localStorage.getItem(k)==="1")return toast("Ya apoyaste este proyecto desde este navegador.");try{const body=new URLSearchParams({action:"support",projectId:id});const r=await fetch(API_URL,{method:"POST",body});const j=await r.json();if(!j.success)throw Error(j.error);localStorage.setItem(k,"1");s.supports[id]=Number(j.count||0);render(s.filtered);toast("¡Gracias por apoyar el talento Ágora! ❤️")}catch(err){console.error(err);toast("No se pudo registrar el apoyo.")}}
function openModal(id){const p=s.projects.find(x=>String(x.id)===String(id));if(!p)return;const m=s.members.filter(x=>String(x.id_proyecto)===String(id)).sort((a,b)=>Number(a.orden||999)-Number(b.orden||999));const img=LOGOS[p.id]||url(p.logo||p.imagen),proto=url(p.prototipo),doc=url(p.documento);e.body.innerHTML=`${img?`<img class="modal-image" src="${attr(img)}" alt="${attr(p.proyecto||"")}">`:""}<div class="modal-info"><div class="meta"><span>🏫 ${esc(p.sede||"")}</span><span>🎓 ${esc(p.grado||p.nivel||"")}</span><span>💡 ${esc(p.categoria||"")}</span></div><h2>${esc(p.proyecto||"")}</h2><p>${esc(p.descripcion_corta||"")}</p>${m.length?`<section class="members"><h3>Integrantes</h3><ul>${m.map(x=>`<li><b>${esc(x.nombre_completo||"")}</b>${x.rol?` — ${esc(x.rol)}`:""}</li>`).join("")}</ul></section>`:""}<div class="actions" style="margin-top:24px">${proto?`<a class="btn primary" href="${attr(proto)}" target="_blank" rel="noopener">Probar prototipo</a>`:""}${doc?`<a class="btn orange" href="${attr(doc)}" target="_blank" rel="noopener">Ver proyecto completo</a>`:""}</div></div>`;e.modal.classList.remove("hidden");document.body.style.overflow="hidden"}
function closeModal(){e.modal.classList.add("hidden");document.body.style.overflow=""}
function toast(t){e.toast.textContent=t;e.toast.classList.remove("hidden");setTimeout(()=>e.toast.classList.add("hidden"),3500)}
function url(v){const m=String(v||"").trim().match(/https?:\/\/[^\s()]+/i);return m?m[0]:""}
function esc(v){return String(v||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
function attr(v){return esc(v)}

